### ISSUE TITLE
Text size limit on all card texts

### ISSUE THREAD

**Issue by guiconti** [bendevorg/buildev#33]

**Comment by miaket** [comment]
Whats the expected behavior that you have in mind?

Something like this?:
![Uploading image.png…]()

**Comment by miaket** [comment]
![image](https://user-images.githubusercontent.com/5157996/47826349-2efc1b00-dd56-11e8-828a-493bbd69d9f0.png)

**Comment by guiconti** [comment]
Yeah!!

**Comment by miaket** [comment]
Is our back sending back any kind of info like that?
I'll for now force the mock to throw something back to the component so we can adapt it later

**Comment by miaket** [comment]
PR open
